version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: training-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${MLFLOW_POSTGRES_USER}
      POSTGRES_PASSWORD: ${MLFLOW_POSTGRES_PASSWORD}
      POSTGRES_DB: ${MLFLOW_POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${MLFLOW_POSTGRES_USER} -d ${MLFLOW_POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20


  training-api:
    image: training-module:rocm
    container_name: training-api
    restart: unless-stopped

    depends_on:
      - mlflow
      - postgres

    ports:
      - "8080:8080"

    devices:
      - /dev/kfd
      - /dev/dri
    
    security_opt:
      - seccomp=unconfined
    
    group_add:
      - video

    environment:
      MLFLOW_TRACKING_URI: http://mlflow:5000
      OS_AUTH_TYPE: ${OS_AUTH_TYPE}
      OS_AUTH_URL: ${OS_AUTH_URL}
      OS_IDENTITY_API_VERSION: ${OS_IDENTITY_API_VERSION}
      OS_REGION_NAME: ${OS_REGION_NAME}
      OS_INTERFACE: ${OS_INTERFACE}
      OS_APPLICATION_CREDENTIAL_ID: ${OS_APPLICATION_CREDENTIAL_ID}
      OS_APPLICATION_CREDENTIAL_SECRET: ${OS_APPLICATION_CREDENTIAL_SECRET}
      OS_PROJECT_ID: ${OS_PROJECT_ID}

    volumes:
      - ../../:/app

    working_dir: /app/Training

    command: >
      uvicorn src.api.train_api:app
      --host 0.0.0.0
      --port 8080

  mlflow:
    image: ghcr.io/mlflow/mlflow:v3.9.0
    container_name: training-mlflow
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      MLFLOW_SERVER_ALLOWED_HOSTS: "*"
      MLFLOW_LOGGING_LEVEL: INFO
    ports:
      - "${MLFLOW_PORT}:5000"
    command: >
      /bin/sh -c "
      pip install psycopg2-binary &&
      mlflow server
      --backend-store-uri postgresql://${MLFLOW_POSTGRES_USER}:${MLFLOW_POSTGRES_PASSWORD}@postgres:5432/${MLFLOW_POSTGRES_DB}
      --host 0.0.0.0
      --port 5000
      "

  prometheus:
    image: prom/prometheus
    container_name: training-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - training-api

  grafana:
    image: grafana/grafana
    container_name: training-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus

volumes:
  postgres_data:
  grafana_data:
  prometheus_data: